project:
  type: website
  output-dir: .

website:
  title: "Présentation du blog"
  navbar:
      right:
      - icon: github
        href: https://github.com/YavaVilar
      - icon: linkedin
        href: https://www.linkedin.com/in/yava-vilar-valera-496999271/
      left:
      - href: about.qmd
      - href: R avancé et Git présentation.qmd

page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto

format:
  html:
    theme: [litera, variables.scss]
    highlight-style: nord

editor: visual

