project:
  type: website

website:
  title: "my_blog"
  navbar:
      right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      left:
      - text: "Exercices semaine 1"
        href: TD1.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    highlight-style: a11y

editor: visual

