project:
  type: website
  output-dir: .

website:
  title: "R avancé et GitHub"
  navbar:
      right:
      - icon: github
        href: https://github.com/YavaVilar
      - text: Email
        url: "vilarvaleray@gmail.com"

page-footer:
    center:
    - text: Email
      url: "vilarvaleray@gmail.com"

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true

editor: visual
