---
title: "Présentation du blog"
about:
  template: jolla
  links:
    - icon: github
      href: https://github.com/YavaVilar
    - icon: linkedin
      href: https://www.linkedin.com/in/yava-vilar-valera-496999271/
    - icon: globe
      href: https://sites.google.com/view/master-ecap/accueil 
---

La création de ce blog s'inscrit dans le cadre d'un projet réalisé pour le cours R avancé et GitHub au sein du Master d'Econométrie Appliquée à l'Université de Nantes. Vous y trouverez deux sections: La première décrit la façon d'installer la librarie créée sous R **`olympicsWeather`**, dont son objectif est de prévoir la météo en temps réél des différents sites olympiques qui auront lieu à Paris pendant l'été 2024, avec des coordonnées GPS ou des noms des lieux fournies par l'utilisateur. Trois exemples de localisation géographique seront montrés. La deuxième section contient trois posts d'articles relatifs aux exercises effectués lors du cours R avancé et GitHub.

Autrice : Yava Vilar Valera

Etudiante en Economie par l'Université de Valence et l'Université de Nantes

Contact: vilarvaleray\@gmail.com
